In [1]:
# https://www.numpy.org/devdocs/user/quickstart.html
import numpy as np

# Ways to Create Array in Numpy

In [2]:
x1 = np.array([2,4,7,8,43,56,78,32,67])

In [3]:
print(x1)

[ 2  4  7  8 43 56 78 32 67]


In [5]:
x2 = np.array([i for i in range(1,100001) if i % 2 == 0])

In [6]:
len(x2)

50000

In [7]:
x2[:10]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
x3 = np.arange(2,10001,2)

In [9]:
len(x3)

5000

In [10]:
x3[:10]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
# will return array of 50 numbers starting from 1.0 to 10.0
# x4 = np.linspace(1,10)

# will return array of 20 numbers starting from 1.0 to 10.0
x4 = np.linspace(1,10, num=20, retstep=True)

In [14]:
x4

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [42]:
np.random.rand(2,5,3)

array([[[0.92313993, 0.62275059, 0.91198084],
        [0.88748464, 0.26442005, 0.18104233],
        [0.6679735 , 0.76404706, 0.55517393],
        [0.79845161, 0.9698211 , 0.17036241],
        [0.47833125, 0.10355383, 0.33095579]],

       [[0.08539692, 0.75773692, 0.58294578],
        [0.70897051, 0.51883831, 0.02078246],
        [0.20798059, 0.45757188, 0.17176757],
        [0.82584859, 0.01273153, 0.32714068],
        [0.50449249, 0.45026179, 0.24074434]]])

In [26]:
# will return 5 random numbers between 10 and 100
np.random.randint(10,100,5)

array([86, 25, 63, 90, 37])

In [27]:
np.random.seed(5)
np.random.randint(10,100,5)

array([88, 71, 26, 83, 18])

In [28]:
np.random.rand()

0.08982103773760686

In [33]:
np.random.seed(5)

In [34]:
np.random.rand()

0.22199317108973948

In [44]:
np.random.random([5,5])

array([[0.51013629, 0.37054469, 0.6626309 , 0.2808777 , 0.65242754],
       [0.80051251, 0.79981042, 0.23051822, 0.47074499, 0.92149262],
       [0.14263597, 0.18287318, 0.14961182, 0.02214987, 0.30185939],
       [0.44315055, 0.96792103, 0.26644357, 0.89248768, 0.49481331],
       [0.23623568, 0.36655306, 0.71858841, 0.36504323, 0.42827433]])

# Methods of Numpy

In [45]:
x = np.random.randint(10,1000,200)

In [46]:
x.max()

995

In [47]:
x.min()

13

In [48]:
x.mean()

491.975

In [49]:
x.shape

(200,)

In [53]:
x.ndim

1

In [51]:
x.argmax()

154

In [54]:
x[154]

995

In [55]:
x.argmin()

76

In [59]:
x.argsort()[:10]

array([ 76, 173,   5,  37, 175,  36,  82, 197,  74,  51], dtype=int64)

# Slicing Numpy Array

In [60]:
x = np.array([[4,5,3,2],[6,8,3,6],[8,8,4,7]])

In [61]:
x

array([[4, 5, 3, 2],
       [6, 8, 3, 6],
       [8, 8, 4, 7]])

In [62]:
x.ndim

2

In [63]:
x.shape

(3, 4)

In [64]:
# in 2d data by default slicing will be row wise
x[0:2]

array([[4, 5, 3, 2],
       [6, 8, 3, 6]])

In [65]:
x[0:2, 0:2]

array([[4, 5],
       [6, 8]])

In [66]:
x[:,0:2]

array([[4, 5],
       [6, 8],
       [8, 8]])