In [18]:
import tensorflow as tf
import numpy as np

# Tensorflow Basics

In [2]:
x = tf.constant(12)
y = tf.constant(16)

In [3]:
z = x + y

In [4]:
sess = tf.Session()

In [5]:
sess.run(z)

28

In [6]:
x = tf.Variable(23)
y = tf.Variable(45)

In [7]:
x+y

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [9]:
z = x + y
init = tf.global_variables_initializer()

In [13]:
with tf.Session() as sess:
    init.run()
    print(sess.run(z))

68


In [15]:
x = tf.placeholder(tf.float32, shape=(5,5))
y = tf.placeholder(tf.float32, shape=(5,1))

In [17]:
opr = tf.matmul(x,y)

In [20]:
arr_1 = np.random.random((5,5))
arr_2 = np.random.random((5,1))

In [21]:
with tf.Session() as sess:
    output = sess.run(opr, feed_dict={x: arr_1, y: arr_2})
    print(output)

[[ 1.31721842]
 [ 1.73446107]
 [ 0.39080143]
 [ 1.11992812]
 [ 0.87655997]]


# Neural Network using Tensorflow

In [31]:
# X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
# y=np.array([[1],[1],[0]])

X = np.random.random((3,4))
y = np.array([[1],[1],[0]])

In [32]:
X.shape

(3, 4)

In [33]:
input_neurons = X.shape[1]
hidden_neurons = 3
output_neurons = 1

In [40]:
weights_hidden = tf.random_uniform((input_neurons, hidden_neurons), dtype=tf.float64)
bias_hidden = tf.random_uniform((1, hidden_neurons), dtype=tf.float64)

weights_output = tf.random_uniform((hidden_neurons, output_neurons), dtype=tf.float64)
bias_output = tf.random_uniform((1, output_neurons), dtype=tf.float64)

In [41]:
# Feedforward
layer_input = tf.matmul(X, weights_hidden)

In [42]:
layer_input

<tf.Tensor 'MatMul_6:0' shape=(3, 3) dtype=float64>

In [43]:
layer = tf.add(layer_input, bias_hidden)

In [44]:
activation = tf.sigmoid(layer)

In [45]:
with tf.Session() as sess:
    print(sess.run(activation))

[[ 0.81886222  0.80765835  0.84754157]
 [ 0.83487041  0.82699766  0.83085422]
 [ 0.89818017  0.86301804  0.89605053]]


# Neural Network 2

In [49]:
n_features = 10
n_dense_neurons = 3
x = tf.placeholder(tf.float32, (None, n_features))

In [50]:
# Bias
b = tf.Variable(tf.zeros([n_dense_neurons]))

# Weight
W = tf.Variable(tf.random_normal([n_features, n_dense_neurons]))

In [58]:
b,W

(<tf.Variable 'Variable_2:0' shape=(3,) dtype=float32_ref>,
 <tf.Variable 'Variable_3:0' shape=(10, 3) dtype=float32_ref>)

In [51]:
xW = tf.matmul(x,W)

In [53]:
z = tf.add(xW,b)

In [54]:
a = tf.sigmoid(z)

In [55]:
init = tf.global_variables_initializer()

In [56]:
with tf.Session() as sess:
    sess.run(init)
    
    layer_out = sess.run(a, feed_dict={x: np.random.random([1, n_features])})
    print(layer_out)

[[ 0.88307661  0.0949328   0.87499237]]
