In [1]:
import tensorflow as tf

In [2]:
x1 = tf.constant(12)
y1 = tf.constant(15)

z1 = x1 + y1

In [3]:
sess = tf.Session()
sess.run(z1)

27

In [4]:
x2 = tf.Variable(21)
y2 = tf.Variable(45)

z2 = x2 + y2

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
init = tf.global_variables_initializer()
sess.run(init)
sess.run(z2)

66

In [8]:
with tf.Session() as sess:
    init.run()
    print(sess.run(z2))

66


In [9]:
zeros = tf.zeros((3,3))
ones = tf.ones((3,3))
rand = tf.random_normal((3,3))

In [11]:
with tf.Session() as sess:
    print(sess.run(zeros))
    print(sess.run(ones))
    print(sess.run(rand))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 0.1059875  -2.1131139   0.15274116]
 [ 0.23342903  0.40512565  0.15874772]
 [ 0.32603788 -0.16567029 -0.6702423 ]]


In [15]:
# placeholders
X = tf.placeholder(tf.float32,shape=(3,5))
y = tf.placeholder(tf.float32,shape=(5,1))

In [16]:
z = tf.matmul(X,y)

In [17]:
import numpy as np

In [18]:
np_x = np.random.random((3,5))
np_y = np.random.random((5,1))

In [20]:
with tf.Session() as sess:
    pred = sess.run(z,feed_dict={X:np_x,y:np_y})
    print(pred)

[[1.239707 ]
 [1.4153222]
 [1.270035 ]]
